<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.2" />
    <xacro:property name="base_width" value="0.18" />
    <xacro:property name="base_height" value="0.16" />
    <xacro:property name="lidar_radius" value="0.025" />
    <xacro:property name="lidar_length" value="0.03" />
    <xacro:property name="wheel_radius" value="0.0425" />
    <xacro:property name="wheel_length" value="0.02" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <link name="base_scan">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 ${lidar_length / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 ${lidar_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${lidar_radius}" l="${lidar_length}"
                                o_xyz="0 0 ${lidar_length / 2.0}" o_rpy="0 0 0" />
    </link>

    <link name="imu_link" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}" /> -->
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}"
                                    o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left" />
    <xacro:wheel_link prefix="right" />

    <xacro:macro name="caster_link" params="prefix">
        <link name="${prefix}_caster_link">
            <visual>
                <geometry>
                    <sphere radius="${wheel_radius / 2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius / 2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2.0}"
                                  o_xyz="0 0 0" o_rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:caster_link prefix="front_left" />
    <xacro:caster_link prefix="front_right" />
    <xacro:caster_link prefix="rear_left" />
    <xacro:caster_link prefix="rear_right" />


    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_scan_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_scan" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 3.14" />
    </joint>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="-0.06 0 0.09" rpy="0 0 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0 ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="0 ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_left_caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="front_left_caster_link" />
        <origin xyz="${base_length / 3.0} ${base_width / 3.0} ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

    <joint name="base_front_right_caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="front_right_caster_link" />
        <origin xyz="${base_length / 3.0} ${-base_width / 3.0} ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

    <joint name="base_rear_left_caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="rear_left_caster_link" />
        <origin xyz="${-base_length / 3.0} ${base_width / 3.0} ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

    <joint name="base_rear_right_caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="rear_right_caster_link" />
        <origin xyz="${-base_length / 3.0} ${-base_width / 3.0} ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

</robot>